/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LazyListImport } from './routes/lazy-list'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const LazyListRoute = LazyListImport.update({
  id: '/lazy-list',
  path: '/lazy-list',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/lazy-list': {
      id: '/lazy-list'
      path: '/lazy-list'
      fullPath: '/lazy-list'
      preLoaderRoute: typeof LazyListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lazy-list': typeof LazyListRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lazy-list': typeof LazyListRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/lazy-list': typeof LazyListRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/lazy-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/lazy-list'
  id: '__root__' | '/' | '/lazy-list'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LazyListRoute: typeof LazyListRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LazyListRoute: LazyListRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/lazy-list"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/lazy-list": {
      "filePath": "lazy-list.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
