/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaginationListRouteImport } from './routes/pagination-list'
import { Route as LazyListRouteImport } from './routes/lazy-list'
import { Route as InformationRouteImport } from './routes/information'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PaginationListRoute = PaginationListRouteImport.update({
  id: '/pagination-list',
  path: '/pagination-list',
  getParentRoute: () => rootRouteImport,
} as any)
const LazyListRoute = LazyListRouteImport.update({
  id: '/lazy-list',
  path: '/lazy-list',
  getParentRoute: () => rootRouteImport,
} as any)
const InformationRoute = InformationRouteImport.update({
  id: '/information',
  path: '/information',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/information': typeof InformationRoute
  '/lazy-list': typeof LazyListRoute
  '/pagination-list': typeof PaginationListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/information': typeof InformationRoute
  '/lazy-list': typeof LazyListRoute
  '/pagination-list': typeof PaginationListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/information': typeof InformationRoute
  '/lazy-list': typeof LazyListRoute
  '/pagination-list': typeof PaginationListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/information' | '/lazy-list' | '/pagination-list'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/information' | '/lazy-list' | '/pagination-list'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/information'
    | '/lazy-list'
    | '/pagination-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  InformationRoute: typeof InformationRoute
  LazyListRoute: typeof LazyListRoute
  PaginationListRoute: typeof PaginationListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pagination-list': {
      id: '/pagination-list'
      path: '/pagination-list'
      fullPath: '/pagination-list'
      preLoaderRoute: typeof PaginationListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lazy-list': {
      id: '/lazy-list'
      path: '/lazy-list'
      fullPath: '/lazy-list'
      preLoaderRoute: typeof LazyListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/information': {
      id: '/information'
      path: '/information'
      fullPath: '/information'
      preLoaderRoute: typeof InformationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  InformationRoute: InformationRoute,
  LazyListRoute: LazyListRoute,
  PaginationListRoute: PaginationListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
